<a href="https://colab.research.google.com/github/rimsharish/python-bootcamp-journey/blob/main/work/day7/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)

[5 7 9]
[ 4 10 18]


In [ ]:
a = np.array([10,20,30,40,50])
print(a.sum())
print(a.mean())
print(a.max())
print(a.min())

150
30.0
50
10


In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({
    "name" : ["ali","sara","john","emma"],
    "age" : [20,22,21,19]
})

In [ ]:
mask = df["age"] > 20
print(mask)

[0    False
1     True
2     True
3    False
Name: age, dtype: bool]


In [ ]:
print(df['age']>20)

0    False
1     True
2     True
3    False
Name: age, dtype: bool


In [ ]:
print(df[df["age"]>20])

   name  age
1  sara   22
2  john   21
